"""MeLoMIA ablations: one definition, one protocol, one table.

Every MeLoMIA ablation in the paper is an arm defined HERE, run through
`configs/experiments/melomia_ablations_{brca,combined}.yaml` (written by this script),
and reported in `results/MELOMIA_ABLATIONS.md` (written by this script).  Nothing else
feeds that table, so any two numbers in it are comparable:

  * same target releases (fingerprints checked), same 5 splits, same 5 generators;
  * same shadow stacks (shadow k is the same model in every arm that uses it);
  * same classifier search: PROTOCOL below, recorded in each meta.json and checked;
  * arms differ only in the factors listed in their row.

Factors: shadow count K, shadows trained on synthetic vs real data, selection by
sample-grouped vs model-disjoint folds, per-record calibration on vs off.

    python scripts/melomia_ablations.py configs     # write the two experiment configs
    python scripts/melomia_ablations.py queue       # ordered "cohort arm" work list
    python scripts/melomia_ablations.py table       # results/MELOMIA_ABLATIONS.md + csv
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
RES = ROOT / "results"

NEW = "pgm@binning=dp_quantile,edge_estimator=threshold,n_bins=16"
GENERATORS = ["mvn", "cvae", "nd", "pgg", NEW]
GEN_LABEL = {"mvn": "MVN", "cvae": "CVAE", "nd": "ND", "pgg": "DP-PGM CAMDA-26", NEW: "DP-PGM new"}
SPLITS = [1, 2, 3, 4, 5]
COHORTS = {"brca": "BRCA", "combined": "COMBINED"}
K_MAX = {"brca": 30, "combined": 20}          # shadows built per cohort
K_SWEEP = {"brca": [5, 10, 15, 20, 30], "combined": [5, 10, 15, 20]}
K_REAL = 15                                   # real-data shadows built per cohort
N_NOISE = {"nd": 600, "cvae": 50}
#: the one classifier search every arm uses
PROTOCOL = {"optuna_trials": 60, "classifiers": ["xgb", "rf", "lgbm", "cat", "mlp"]}


def arms(cohort: str) -> dict:
    """label -> dict(backend, K, shadows, selection, calibration, priority)."""
    out = {}

    def add(be, K, shadows="synth", selection="grouped", cal=True, priority=1):
        lab = f"{be}_k{K}"
        if shadows == "real":
            lab += "_real"
        if selection == "block":
            lab += "_block"
        lab += "_cal" if cal else "_raw"
        out[lab] = dict(backend=be, K=K, shadows=shadows, selection=selection,
                        calibration=cal, priority=priority)

    for be in ("nd", "cvae"):
        for cal in (True, False):
            for K in K_SWEEP[cohort]:
                # calibrated arms first; the headline K is already fitted
                add(be, K, cal=cal, priority=0 if K == K_MAX[cohort] else (1 if cal else 3))
            add(be, K_REAL, shadows="real", cal=cal, priority=1 if cal else 2)
            add(be, K_MAX[cohort], selection="block", cal=cal,
                priority=(2 if cal else 3) if cohort == "brca" else 4)
    return out


def arm_params(a: dict) -> dict:
    return {"n_shadows": a["K"], "n_noise": N_NOISE[a["backend"]], **PROTOCOL,
            "synth_shadow": a["shadows"] == "synth",
            "internal_proxy_selection": a["selection"] == "block",
            "per_record_calibration": a["calibration"]}


def arm_tag(a: dict) -> str:
    t = f"k{a['K']}_n{N_NOISE[a['backend']]}"
    if a["shadows"] == "real":
        t += "_realshadow"
    if a["selection"] == "block":
        t += "_blockcv"
    if a["calibration"]:
        t += "_prc"
    return t


def write_configs():
    for low, ds in COHORTS.items():
        cfg = {
            "name": f"melomia_ablations_{low}", "dataset": ds, "device": "cuda",
            "notes": "MeLoMIA ablations, one protocol; arms defined in scripts/melomia_ablations.py",
            "generators": GENERATORS, "splits": SPLITS,
            "attacks": {lab: {"class": f"melomia_{a['backend']}", "params": arm_params(a)}
                        for lab, a in arms(low).items()},
        }
        p = ROOT / "configs" / "experiments" / f"melomia_ablations_{low}.yaml"
        p.write_text("# GENERATED by scripts/melomia_ablations.py configs -- edit the arms there.\n"
                     + yaml.safe_dump(cfg, sort_keys=False, width=120))
        print("wrote", p.relative_to(ROOT), f"({len(cfg['attacks'])} arms)")


def queue():
    rows = [(a["priority"], i, low, lab) for i, low in enumerate(COHORTS)
            for lab, a in arms(low).items()]
    for _, _, low, lab in sorted(rows):
        print(low, lab)


# ── table ───────────────────────────────────────────────────────────────────

def _fmt(v, sd=None):
    return "—" if v is None or np.isnan(v) else (f"{v:.3f}" if sd is None else f"{v:.3f} ± {sd:.3f}")


def table():
    from mia import targets as T
    idx = pd.read_csv(RES / "index.csv")
    idx = idx[idx.experiment.isin([f"melomia_ablations_{c}" for c in COHORTS])]
    idx = idx.sort_values("timestamp").drop_duplicates(
        ["dataset", "variant", "generator", "split"], keep="last")
    problems, runs, arm_rows = [], [], []

    for low, ds in COHORTS.items():
        fps = {(g, s): T.fingerprint(ds, g, s) for g in GENERATORS for s in SPLITS}
        for lab, a in arms(low).items():
            sub = idx[(idx.dataset == ds) & (idx.variant == lab)]
            want = arm_params(a)
            for _, r in sub.iterrows():
                cfg = json.loads((RES / "runs" / r.run_id / "config.json").read_text())
                bad = {k: (cfg["params"].get(k), v) for k, v in want.items()
                       if cfg["params"].get(k) != v}
                if bad:
                    problems.append(f"{ds} {lab} {r.generator} s{r.split}: params differ {bad}")
                if cfg["tag"] != arm_tag(a):
                    problems.append(f"{ds} {lab}: tag {cfg['tag']} != {arm_tag(a)}")
                if cfg["target"]["fingerprint"] != fps[(r.generator, r.split)]:
                    problems.append(f"{ds} {lab} {r.generator} s{r.split}: scored a different "
                                    "release than the current target")
                runs.append({"cohort": ds, "arm": lab, **{k: a[k] for k in
                             ("backend", "K", "shadows", "selection", "calibration")},
                             "generator": r.generator, "split": r.split, "auc": r.auc,
                             "aupr": r.aupr, "tpr_at_fpr_0.01": r["tpr_at_fpr_0.01"],
                             "tpr_at_fpr_0.1": r["tpr_at_fpr_0.1"], "n": r.n,
                             "n_members": r.n_members, "tag": cfg["tag"], "run_id": r.run_id,
                             "target_fingerprint": cfg["target"]["fingerprint"],
                             "timestamp": r.timestamp})
            stack = f"n{N_NOISE[a['backend']]}" + ("_realshadow" if a["shadows"] == "real" else "")
            mp = (ROOT / "artifacts" / "attacks" / f"melomia_{a['backend']}" / ds / stack
                  / "meta" / arm_tag(a) / "meta.json")
            row = {"cohort": ds, "arm": lab, **a, "tag": arm_tag(a), "runs": len(sub),
                   "meta": mp.exists()}
            if mp.exists():
                m = json.loads(mp.read_text())
                row["protocol_source"] = m.get("protocol_source", "not recorded")
                pr = m.get("protocol") or {}
                bad = {k: (pr.get(k), v) for k, v in want.items() if k in pr and pr[k] != v}
                if bad or not pr:
                    problems.append(f"{ds} {lab}: meta.json protocol "
                                    + (f"differs {bad}" if bad else "not recorded"))
                w = m["ensemble_weights"]
                row["cv_auc"] = float(sum(w[c] * m["classifiers"][c]["cv"]["auc"] for c in w))
                row["cv_scheme"] = m.get("selection", "grouped")
            if 0 < len(sub) < len(GENERATORS) * len(SPLITS):
                problems.append(f"{ds} {lab}: {len(sub)} of {len(GENERATORS) * len(SPLITS)} runs")
            arm_rows.append(row)

    R, A = pd.DataFrame(runs), pd.DataFrame(arm_rows)
    if len(R):
        g = R.groupby(["cohort", "generator", "split"])
        if (g.n.nunique() > 1).any() or (g.n_members.nunique() > 1).any():
            problems.append("candidate pool size differs between arms for the same target")
    R.to_csv(RES / "melomia_ablations.csv", index=False)
    A.drop(columns=["priority"]).to_csv(RES / "melomia_ablations_arms.csv", index=False)

    def cell(ds, lab, gen, col="auc"):
        v = R[(R.cohort == ds) & (R.arm == lab) & (R.generator == gen)][col] if len(R) else []
        return _fmt(None) if len(v) == 0 else _fmt(v.mean()) + ("" if len(v) == 5 else f" ({len(v)})")

    def block(ds, low, title, labs, names, note=""):
        L = [f"### {title}", ""] + ([note, ""] if note else [])
        for be in ("nd", "cvae"):
            L += [f"**MeLoMIA-{be.upper()}, {ds}** (AUC; TPR at 1% FPR in brackets)", "",
                  "| Arm | Cross-validated AUC | " + " | ".join(GEN_LABEL[g] for g in GENERATORS) + " |",
                  "|---|---|" + "---|" * len(GENERATORS)]
            for lab, name in zip(labs, names):
                lab = lab.format(be=be)
                if lab not in arms(low):
                    continue
                cv = A[(A.cohort == ds) & (A.arm == lab)].get("cv_auc")
                cvs = _fmt(cv.iloc[0]) if cv is not None and len(cv) and pd.notna(cv.iloc[0]) else "—"
                L.append(f"| {name} | {cvs} | " + " | ".join(
                    f"{cell(ds, lab, g)} [{cell(ds, lab, g, 'tpr_at_fpr_0.01')}]"
                    if cell(ds, lab, g) != "—" else "pending" for g in GENERATORS) + " |")
            L.append("")
        return L

    L = ["# MeLoMIA ablations", "",
         "Generated by `python scripts/melomia_ablations.py table`; arms are defined in that script.",
         "Per-run rows: `results/melomia_ablations.csv`.  Per-arm rows (tag, cross-validated AUC, "
         "where the protocol record came from): `results/melomia_ablations_arms.csv`.", "",
         "**Protocol, identical in every arm.** Black box. 5 generators × splits 1–5 of each cohort "
         "(the slide-table targets, fingerprints checked). Classifier search: Optuna, "
         f"{PROTOCOL['optuna_trials']} trials per classifier, ensemble of "
         f"{', '.join(PROTOCOL['classifiers'])}. Feature grids: 600 frozen draws × 15 timesteps "
         "(ND), 50 draws × 6 temperatures (CVAE). Shadow k is the same model in every arm. "
         "Cells are means over 5 splits; \"(n)\" marks fewer. \"Cross-validated AUC\" is the "
         "attacker's own estimate on shadows, never an attack result.", ""]
    for low, ds in COHORTS.items():
        K = K_MAX[low]
        L += [f"## {ds}", ""]
        L += block(ds, low, f"A. Per-record calibration (K = {K} synth-shadows)",
                   [f"{{be}}_k{K}_raw", f"{{be}}_k{K}_cal"],
                   ["Without calibration", "With per-record calibration"])
        L += block(ds, low, f"B. Synth-shadows vs real-data shadows (K = {K_REAL})",
                   [f"{{be}}_k{K_REAL}_raw", f"{{be}}_k{K_REAL}_real_raw",
                    f"{{be}}_k{K_REAL}_cal", f"{{be}}_k{K_REAL}_real_cal"],
                   ["Synth-shadows, no calibration", "Real shadows, no calibration",
                    "Synth-shadows, calibrated", "Real shadows, calibrated"],
                   "Shadows are trained on a base shadow's synthetic data (the method) or directly "
                   "on real splits (the ablation); the proxy is the same model either way.")
        L += block(ds, low, f"C. Selection folds (K = {K})",
                   [f"{{be}}_k{K}_raw", f"{{be}}_k{K}_block_raw",
                    f"{{be}}_k{K}_cal", f"{{be}}_k{K}_block_cal"],
                   ["Sample-grouped, no calibration", "Model-disjoint, no calibration",
                    "Sample-grouped, calibrated", "Model-disjoint, calibrated"])
        L += block(ds, low, "D. Number of synth-shadows",
                   [f"{{be}}_k{k}_{c}" for c in ("raw", "cal") for k in K_SWEEP[low]],
                   [f"K = {k}, {'calibrated' if c == 'cal' else 'no calibration'}"
                    for c in ("raw", "cal") for k in K_SWEEP[low]])
    done = int((A.runs == len(GENERATORS) * len(SPLITS)).sum()) if len(A) else 0
    L += ["## Consistency checks", "",
          f"{done} of {len(A)} arms complete.  Checked for every run: recorded parameters equal "
          "the arm's definition; tag as expected; the release scored is the current target; "
          "candidate pool identical across arms; the cached classifier's recorded protocol.", ""]
    L += [f"- **PROBLEM** {p}" for p in sorted(set(problems))] or ["No discrepancies found."]
    (RES / "MELOMIA_ABLATIONS.md").write_text("\n".join(L) + "\n")
    print(f"{done}/{len(A)} arms complete; {len(set(problems))} problems; wrote results/MELOMIA_ABLATIONS.md")
    for p in sorted(set(problems))[:20]:
        print("  PROBLEM", p)


if __name__ == "__main__":
    {"configs": write_configs, "queue": queue, "table": table}[sys.argv[1]]()
