#!/usr/bin/env python
"""The group-meeting table: every attack and fidelity metric, five generators.

    python scripts/slide_table.py

For Steven (2026-09-27).  Columns are MVN, CVAE, ND, DP-PGM old (the CAMDA-25
generator, `neighboring=legacy_exact_n`) and DP-PGM new (star, zCDP, 16 DP
equal-depth bins).  Every cell is the mean over the splits that have a run,
taking the LATEST run per split for the attack's as-configured tag, so a
cell always reflects the current target and the current code.  Cells with
fewer than 5 splits are marked.  Fidelity is computed here for any
(cohort, generator, split) not yet in results/fidelity_slides.csv, with the
same `fidelity.evaluate` call as scripts/fidelity_grid.py.

Writes results/SLIDE_TABLE.md and results/slide_table.csv.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

for _v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS"):
    os.environ.setdefault(_v, "4")
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from mia import datasets as D  # noqa: E402
from mia import fidelity as F  # noqa: E402
from mia import targets as T  # noqa: E402

RES = ROOT / "results"
OLD = "pgm@composition=basic,neighboring=legacy_exact_n"
NEW = "pgm@binning=dp_quantile,edge_estimator=threshold,n_bins=16"
COLS = [("mvn", "MVN"), ("cvae", "CVAE"), ("nd", "ND"),
        (OLD, "DP-PGM old"), (NEW, "DP-PGM new")]
K = {"BRCA": 30, "COMBINED": 20}
GENERIC = {"mc": "MC", "gan_leaks": "GAN-leaks", "conf_lr": "Conf-LR",
           "conf_rf": "Conf-RF", "logan_d1": "LOGAN", "gan_leaks_cal": "GAN-leaks-cal",
           "domias_kde": "DOMIAS-KDE"}
FID = [("utility_ratio", "Utility (TSTR / real, higher is better)"),
       ("corr_mae", "Gene-gene correlation error (lower is better)"),
       ("wasserstein_mean", "Per-gene distribution distance, W1 (lower is better)")]


def fidelity() -> pd.DataFrame:
    path = RES / "fidelity_slides.csv"
    have = pd.read_csv(path) if path.exists() else pd.DataFrame()
    grid = pd.read_csv(RES / "fidelity_grid.csv")
    rows = []
    for ds in ("BRCA", "COMBINED"):
        X = D.load_expression(ds).values.astype(np.float64)
        y = D.encode_subtypes(ds, D.load_subtypes(ds).values)
        for gen, _ in COLS:
            for s in range(1, 6):
                if not T.exists(ds, gen, s):
                    continue
                fp = T.target_record(ds, gen, s)["fingerprint"]
                for src in (have, grid):
                    hit = src[(src.get("fingerprint") == fp)] if len(src) else src
                    if len(hit):
                        rows.append({**hit.iloc[-1].to_dict(), "dataset": ds,
                                     "generator": gen, "split": s})
                        break
                else:
                    tg = T.load_target(ds, gen, s)
                    m = D.membership_labels(ds, s).astype(bool)
                    r = F.evaluate(tg["X"].astype(np.float64), tg["y_int"],
                                   X[~m], y[~m], X[m], y[m])
                    rows.append({**r, "dataset": ds, "generator": gen, "split": s,
                                 "fingerprint": fp})
                    print(f"  fidelity {ds} {gen} s{s}", flush=True)
    out = pd.DataFrame(rows)
    out.to_csv(path, index=False)
    return out


def attack_rows(ds: str) -> list[tuple[str, str, str]]:
    k = K[ds]
    rows = [("MahalaMIA", "mahalamia", "aux"),
            ("MeLoMIA-CVAE", "melomia_cvae", f"k{k}_n50"),
            ("MeLoMIA-ND", "melomia_nd", f"k{k}_n600"),
            ("MAMA-MIA v1", "mamamia", "k4_1w_2w"),
            ("MAMA-MIA v2 (black box)", "mamamia_v2", "cl-public_ed-auto_cc")]
    rows += [(f"  {GENERIC[m]}", "generic", m) for m in GENERIC
             if ds == "COMBINED" or m not in ("logan_d1", "gan_leaks_cal", "domias_kde")]
    return rows


def cell(v: pd.Series) -> str:
    if v.empty:
        return "—"
    s = f"{v.mean():.3f}"
    return s if len(v) == 5 else f"{s} ({len(v)} splits)"


def main():
    idx = pd.read_csv(RES / "index.csv").sort_values("timestamp")
    idx = idx.drop_duplicates(["dataset", "attack", "tag", "generator", "split"], keep="last")
    fid = fidelity()
    L = ["# Slide table: attacks and fidelity, five generators", "",
         "Generated by `scripts/slide_table.py`.  Mean over splits (5 unless marked), "
         "latest run per split.  eps = 10 for both DP-PGMs.", ""]
    csv = []
    for ds in ("BRCA", "COMBINED"):
        L += [f"## {ds}", "", "| | " + " | ".join(n for _, n in COLS) + " |",
              "|---|" + "---|" * len(COLS)]
        for col, name in FID:
            vals = []
            for gen, _ in COLS:
                v = fid[(fid.dataset == ds) & (fid.generator == gen)][col]
                vals.append(cell(v))
                csv.append({"dataset": ds, "row": name, "generator": gen,
                            "mean": v.mean() if len(v) else np.nan, "n": len(v)})
            L.append(f"| {name} | " + " | ".join(vals) + " |")
        best = {gen: [] for gen, _ in COLS}
        for name, atk, tag in attack_rows(ds):
            vals = []
            for gen, _ in COLS:
                v = idx[(idx.dataset == ds) & (idx.attack == atk) & (idx.tag == tag)
                        & (idx.generator == gen)].auc
                vals.append(cell(v))
                if atk == "generic" and len(v):
                    best[gen].append((v.mean(), name.strip()))
                csv.append({"dataset": ds, "row": name.strip(), "generator": gen,
                            "mean": v.mean() if len(v) else np.nan, "n": len(v)})
            L.append(f"| {name} | " + " | ".join(vals) + " |")
        L.append("| Best generic attack | " + " | ".join(
            (f"{max(best[g])[0]:.3f} ({max(best[g])[1]})" if best[g] else "—")
            for g, _ in COLS) + " |")
        L.append("")
    (RES / "SLIDE_TABLE.md").write_text("\n".join(L))
    pd.DataFrame(csv).to_csv(RES / "slide_table.csv", index=False)
    print("\n".join(L))


if __name__ == "__main__":
    main()
